// Estrutura REAL dos 114 leitos do Natus Lumine (censo SPDATA 30/06/2026, com ajustes do gestor).
// modo: todos os leitos operam em modo paciente (o próprio ocupante usa o app).
export const LEITOS = [
  { numero: "307", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "308", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "enfermaria", modo: "paciente" },
  { numero: "309", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "310", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "enfermaria", modo: "paciente" },
  { numero: "311", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "312", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "enfermaria", modo: "paciente" },
  { numero: "313", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "314", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "315", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "316", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "317", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "318", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "319", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "320", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "321", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "323", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "325", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "327", setor: "UNI Adulto Rosa", andar: "1\u00ba andar", posto: "Rosa", acomod: "apartamento", modo: "paciente" },
  { numero: "114", setor: "UNI Adulto Azul", andar: "S1", posto: "Azul", acomod: "apartamento", modo: "paciente" },
  { numero: "117", setor: "UNI Adulto Azul", andar: "S1", posto: "Azul", acomod: "apartamento", modo: "paciente" },
  { numero: "119", setor: "UNI Adulto Azul", andar: "S1", posto: "Azul", acomod: "apartamento", modo: "paciente" },
  { numero: "123", setor: "UNI Adulto Azul", andar: "S1", posto: "Azul", acomod: "apartamento", modo: "paciente" },
  { numero: "125", setor: "UNI Adulto Azul", andar: "S1", posto: "Azul", acomod: "apartamento", modo: "paciente" },
  { numero: "126", setor: "UNI Adulto Azul", andar: "S1", posto: "Azul", acomod: "apartamento", modo: "paciente" },
  { numero: "140", setor: "UNI Adulto Azul", andar: "S1", posto: "Azul", acomod: "apartamento", modo: "paciente" },
  { numero: "142", setor: "UNI Adulto Azul", andar: "S1", posto: "Azul", acomod: "apartamento", modo: "paciente" },
  { numero: "144", setor: "UNI Adulto Azul", andar: "S1", posto: "Azul", acomod: "apartamento", modo: "paciente" },
  { numero: "146", setor: "UNI Adulto Azul", andar: "S1", posto: "Azul", acomod: "apartamento", modo: "paciente" },
  { numero: "121", setor: "Posto Pedi\u00e1trico", andar: "S1", posto: "Azul", acomod: "enfermaria", modo: "paciente" },
  { numero: "122", setor: "Posto Pedi\u00e1trico", andar: "S1", posto: "Azul", acomod: "enfermaria", modo: "paciente" },
  { numero: "124", setor: "Posto Pedi\u00e1trico", andar: "S1", posto: "Azul", acomod: "enfermaria", modo: "paciente" },
  { numero: "127", setor: "Posto Pedi\u00e1trico", andar: "S1", posto: "Azul", acomod: "enfermaria", modo: "paciente" },
  { numero: "129", setor: "Posto Pedi\u00e1trico", andar: "S1", posto: "Azul", acomod: "enfermaria", modo: "paciente" },
  { numero: "131", setor: "Posto Pedi\u00e1trico", andar: "S1", posto: "Azul", acomod: "enfermaria", modo: "paciente" },
  { numero: "133", setor: "Posto Pedi\u00e1trico", andar: "S1", posto: "Azul", acomod: "enfermaria", modo: "paciente" },
  { numero: "135", setor: "Posto Pedi\u00e1trico", andar: "S1", posto: "Azul", acomod: "enfermaria", modo: "paciente" },
  { numero: "116", setor: "Posto Pedi\u00e1trico", andar: "S1", posto: "Azul", acomod: "enfermaria", modo: "paciente" },
  { numero: "118", setor: "Posto Pedi\u00e1trico", andar: "S1", posto: "Azul", acomod: "enfermaria", modo: "paciente" },
  { numero: "120", setor: "Posto Pedi\u00e1trico", andar: "S1", posto: "Azul", acomod: "enfermaria", modo: "paciente" },
  { numero: "201", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "202", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "203", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "204", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "205", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "206", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "207", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "208", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "209", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "210", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "211", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "212", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "213", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "214", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "215", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "216", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "217", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "218", setor: "UNI Adulto Amarelo", andar: "Portaria", posto: "Amarelo", acomod: "enfermaria", modo: "paciente" },
  { numero: "301", setor: "Su\u00edte UNI Verde", andar: "1\u00ba andar", posto: "Verde", acomod: "suite", modo: "paciente" },
  { numero: "302", setor: "Su\u00edte UNI Verde", andar: "1\u00ba andar", posto: "Verde", acomod: "suite", modo: "paciente" },
  { numero: "303", setor: "Su\u00edte UNI Verde", andar: "1\u00ba andar", posto: "Verde", acomod: "suite", modo: "paciente" },
  { numero: "304", setor: "Su\u00edte UNI Verde", andar: "1\u00ba andar", posto: "Verde", acomod: "suite", modo: "paciente" },
  { numero: "305", setor: "Su\u00edte UNI Verde", andar: "1\u00ba andar", posto: "Verde", acomod: "suite", modo: "paciente" },
  { numero: "306", setor: "Su\u00edte UNI Verde", andar: "1\u00ba andar", posto: "Verde", acomod: "suite", modo: "paciente" },
  { numero: "101", setor: "UTI Adulto 1", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "102", setor: "UTI Adulto 1", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "103", setor: "UTI Adulto 1", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "104", setor: "UTI Adulto 1", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "105", setor: "UTI Adulto 1", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "106", setor: "UTI Adulto 1", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "107", setor: "UTI Adulto 1", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "108", setor: "UTI Adulto 1", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "109", setor: "UTI Adulto 1", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "110", setor: "UTI Adulto 1", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "111", setor: "UTI Adulto 1", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "112", setor: "UTI Adulto 1", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "113", setor: "UTI Adulto 1", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "115", setor: "UTI Adulto 1", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-220", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-221", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-222", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-223", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-224", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-225", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-226", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-227", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-228", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-229", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-230", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-231", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-232", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-233", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-234", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "SEAD-235", setor: "UTI Adulto 2", andar: "Portaria", posto: "Amarelo", acomod: "leito_uti", modo: "paciente" },
  { numero: "NEO-322", setor: "UTI Neonatal", andar: "1\u00ba andar", posto: "Rosa", acomod: "leito_uti", modo: "paciente" },
  { numero: "NEO-324", setor: "UTI Neonatal", andar: "1\u00ba andar", posto: "Rosa", acomod: "leito_uti", modo: "paciente" },
  { numero: "NEO-326", setor: "UTI Neonatal", andar: "1\u00ba andar", posto: "Rosa", acomod: "leito_uti", modo: "paciente" },
  { numero: "NEO-328", setor: "UTI Neonatal", andar: "1\u00ba andar", posto: "Rosa", acomod: "leito_uti", modo: "paciente" },
  { numero: "NEO-329", setor: "UTI Neonatal", andar: "1\u00ba andar", posto: "Rosa", acomod: "leito_uti", modo: "paciente" },
  { numero: "NEO-330", setor: "UTI Neonatal", andar: "1\u00ba andar", posto: "Rosa", acomod: "leito_uti", modo: "paciente" },
  { numero: "NEO-331", setor: "UTI Neonatal", andar: "1\u00ba andar", posto: "Rosa", acomod: "leito_uti", modo: "paciente" },
  { numero: "NEO-332", setor: "UTI Neonatal", andar: "1\u00ba andar", posto: "Rosa", acomod: "leito_uti", modo: "paciente" },
  { numero: "NEO-333", setor: "UTI Neonatal", andar: "1\u00ba andar", posto: "Rosa", acomod: "leito_uti", modo: "paciente" },
  { numero: "NEO-335", setor: "UTI Neonatal", andar: "1\u00ba andar", posto: "Rosa", acomod: "leito_uti", modo: "paciente" },
  { numero: "NEO-337", setor: "UTI Neonatal", andar: "1\u00ba andar", posto: "Rosa", acomod: "leito_uti", modo: "paciente" },
  { numero: "128", setor: "UTI Pedi\u00e1trica", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "130", setor: "UTI Pedi\u00e1trica", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "132", setor: "UTI Pedi\u00e1trica", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "134", setor: "UTI Pedi\u00e1trica", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "136", setor: "UTI Pedi\u00e1trica", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "137", setor: "UTI Pedi\u00e1trica", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "139", setor: "UTI Pedi\u00e1trica", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "141", setor: "UTI Pedi\u00e1trica", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "143", setor: "UTI Pedi\u00e1trica", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
  { numero: "145", setor: "UTI Pedi\u00e1trica", andar: "S1", posto: "Azul", acomod: "leito_uti", modo: "paciente" },
];
